[project]
name = "bemcp"
version = "0.1.5"
description = "A MCP Manager for LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["bemcp*"]
